spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dmsdb
spring.datasource.username=postgres
spring.datasource.password=03122000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
aws.accessKey = AKIATVHSDQ54HWV6NVEC
aws.secretKey = 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
aws.region = eu-north-1
aws.bucket = bankdms
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB