spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dmsdb
spring.datasource.username=postgres
spring.datasource.password=03122000
# To hibernate update the table entities
spring.jpa.hibernate.ddl-auto=update
# Wait for Hibernate to create the schema before executing data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
aws.accessKey = AKIATVHSDQ54HWV6NVEC
aws.secretKey = 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
aws.region = eu-north-1
aws.bucket = bankdms

# To define teh file size to store large files
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# to insert data into table using data sql file
spring.sql.init.mode=always
spring.sql.init.data-location=classpath:data.sql
